services:
  postgres:
    image: postgres:15
    container_name: go-forum-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goforum
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  readyset:
    image: readysettech/readyset:latest
    container_name: go-forum-rs
    restart: unless-stopped
    environment:
      UPSTREAM_DB_URL: postgresql://postgres:postgres@postgres:5432/goforum
      LISTEN_ADDRESS: 0.0.0.0:5433
      DEPLOYMENT_ENV: quickstart_docker
      QUERY_LOG_MODE: verbose # disabled, enabled, verbose
    command: ["--prometheus-metrics", "--disable-telemetry"]
    ports:
      - "5433:5433"
      - "6034:6034"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6034/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  aide:
    image: ghcr.io/birabittoh/aide:latest
    container_name: aide
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/models
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  postgres_data:
