services:
  go-forum:
    image: ghcr.io/birabittoh/go-forum:main
    build: .
    container_name: go-forum
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./data:/app/data
